version: '3'
services:
  server:
    build: .
    environment:
      SPRING_APPLICATION_JSON: '{
           "spring.datasource.url"  : "jdbc:mysql://db:3306/timetable"
         }'
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: on-failure
    networks:
      - backend

  db:
    image: mysql:8.0
    platform: linux/x86_64
    restart: always
    command: --init-file /data/application/init.sql
    volumes:
      - ./init.sql:/data/application/init.sql
    environment:
      - MYSQL_DATABASE=timetable
      - MYSQL_ROOT_PASSWORD=pass
    ports:
      - "3306:3306"
    networks:
      - backend

networks:
  backend:

