name: Java CI

on: 
  push:
    branches-ignore: [master, main, back_development]
    # Remove the line above to run when pushing to master
  pull_request:
    branches: [master, main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build with Maven
        run: | 
          cd src/backend/TimetableLinkAPI 
          mvn --batch-mode --update-snapshots package
      - name: Run the Maven verify phase
        run: |
          cd src/backend/TimetableLinkAPI 
          mvn --batch-mode --update-snapshots verify
